[package]
name = "affine_storage"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
jwst-codec = { git = "https://github.com/toeverything/OctoBase.git" }
jwst-core = { git = "https://github.com/toeverything/OctoBase.git" }
jwst-storage = { git = "https://github.com/toeverything/OctoBase.git" }
napi = { version = "2", default-features = false, features = [
  "napi5",
  "async",
] }
napi-derive = { version = "2", features = ["type-def"] }

[build-dependencies]
napi-build = "2"
