[workspace]
resolver = "2"
members = [
  "./packages/native",
  "./packages/native/schema",
  "./packages/storage",
]

[profile.dev.package.sqlx-macros]
opt-level = 3

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
strip = "symbols"
